name: hhsuite3-binderized
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  #- qgrid 
  - jupyterlab>=2.0
  - pandas-datareader>=0.5.0
  - matplotlib>=2.1.1
  - seaborn
  - statsmodels
  - numpy
  - biopython
  - regex
  - blast>=2.7.1
  - papermill
  - hhsuite
  - nbgitpuller
  - pip
  - pip:
    - https://github.com/intermine/intermine-ws-python/archive/dev.zip
    - openpyxl
    - jupytext
    - snakemake
