#!/bin/bash


# based on https://github.com/soedinglab/pdbx and https://www.devdungeon.com/content/how-build-python-source
git clone https://github.com/soedinglab/pdbx.git

mkdir build
cd build
cmake -DUserInstallOption=ON ../
make install